version: '3.7'

services:
  app:
    build: .
    command: flask run --host ${APP_HOST} --port ${APP_PORT}
    restart: unless-stopped
    environment:
      # Pass predefined env variables from .env file.
      - FLASK_APP
      - FLASK_ENV
      - SECRET_KEY
